#!/usr/bin/env python3
"""Generate the synthetic print-stock cubes shipped in data/prints/.

These are PLACEHOLDERS: process-informed parametric stylizations of what
print emulsions do, generated by this script, measured from nothing. Every
stem carries the synthetic_ prefix and every cube's TITLE says so. They
exist so the print axis (negative -> print chaining) is demonstrable out
of the box; drop measured print cubes (Kodak 2383/2393, Fuji 3513 class)
into the film library to supersede them.

Regenerate with:  python3 tools/make_print_cubes.py
"""
import math
import os

SIZE = 17
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "prints")


def clamp01(x):
    return 0.0 if x < 0.0 else (1.0 if x > 1.0 else x)


def luma(r, g, b):
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def shoulder(v, strength):
    """Gentle filmic highlight rolloff, anchored so mid-gray moves little."""
    return v / (1.0 + strength * v * v * v)


def saturate(r, g, b, amount):
    y = luma(r, g, b)
    return (y + (r - y) * amount, y + (g - y) * amount, y + (b - y) * amount)


def contrast(v, amount, pivot=0.44):
    return pivot + (v - pivot) * amount


def cine_print(r, g, b):
    """Projection print: crushed toe, rolled shoulder, teal-leaning
    shadows, mild gamut compression - the theatrical look."""
    y = luma(r, g, b)
    shadow = (1.0 - y) ** 2.2
    r, g, b = r - 0.030 * shadow, g - 0.006 * shadow, b + 0.028 * shadow
    r, g, b = (shoulder(v, 0.22) for v in (r, g, b))
    r, g, b = saturate(r, g, b, 0.93)
    r, g, b = (contrast(v, 1.10, 0.42) for v in (r, g, b))
    # toe crush: projection blacks are deep
    r, g, b = (v - 0.035 * (1.0 - v) ** 6 for v in (r, g, b))
    return r, g, b


def minilab(r, g, b):
    """Consumer lab print: warm midtones, snappy contrast, a little extra
    saturation - the one-hour-photo envelope look."""
    y = luma(r, g, b)
    mid = 4.0 * y * (1.0 - y)
    r, g, b = r + 0.020 * mid, g + 0.008 * mid, b - 0.012 * mid
    r, g, b = saturate(r, g, b, 1.08)
    r, g, b = (contrast(v, 1.14) for v in (r, g, b))
    r, g, b = (shoulder(v, 0.10) for v in (r, g, b))
    return r, g, b


def archival_neutral(r, g, b):
    """Near-neutral archival print: gentle shoulder, hair of desaturation.
    The safe placeholder that mostly demonstrates the chain itself."""
    r, g, b = (shoulder(v, 0.08) for v in (r, g, b))
    return saturate(r, g, b, 0.985)


STOCKS = {
    "synthetic_cine_print": (cine_print,
        "SYNTHETIC projection-print stylization - generated, not measured"),
    "synthetic_minilab": (minilab,
        "SYNTHETIC consumer-lab stylization - generated, not measured"),
    "synthetic_archival_neutral": (archival_neutral,
        "SYNTHETIC near-neutral print - generated, not measured"),
}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for stem, (fn, title) in STOCKS.items():
        path = os.path.join(OUT_DIR, stem + ".cube")
        with open(path, "w") as f:
            f.write('TITLE "%s"\n' % title)
            f.write("LUT_3D_SIZE %d\n" % SIZE)
            for bi in range(SIZE):
                for gi in range(SIZE):
                    for ri in range(SIZE):
                        r = ri / (SIZE - 1)
                        g = gi / (SIZE - 1)
                        b = bi / (SIZE - 1)
                        ro, go, bo = fn(r, g, b)
                        f.write("%.6f %.6f %.6f\n" % (
                            clamp01(ro), clamp01(go), clamp01(bo)))
        print("wrote", path)


if __name__ == "__main__":
    main()
